[project]
name = "fortiartifacts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=3.4.0",
    "pre-commit>=4.4.0",
    "pyyaml>=6.0.1",
]
